image:
  - Visual Studio 2019

environment:
  matrix:
    # Win32/x86/Debug
    - platform: Win32
      configuration: Debug
      cmake_args: -DCMAKE_SYSTEM_VERSION="10.0.18362.0"
      platform_name: Windows

# clone directory
clone_folder: c:\projects\zeloengine

cache:
  - c:\tools\vcpkg\installed
  - c:\projects\zeloengine\dep

install:
  - cd c:\projects\zeloengine
  - tools\setup\setup_appveyor.bat

before_build:
  - cd c:\projects\zeloengine
  - echo %PLATFORM%
  - echo.%cmake_args%
  - cmake %cmake_args% -S . -B ./build -G "Visual Studio 16 2019" -A %PLATFORM%

build:
  project: '%APPVEYOR_BUILD_FOLDER%\build\ZeloEngine.sln'
  verbosity: minimal
  parallel: true
