image:
  - Visual Studio 2019

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    # Win32/x86/Debug
    - platform: Win32
      configuration: Debug
      cmake_args: -DCMAKE_SYSTEM_VERSION="10.0.18362.0"
      platform_name: Windows
      COMPILER: MSVC_16
      ARCHITECTURE: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# clone directory
clone_folder: c:\projects\zeloengine

cache:
  - c:\tools\vcpkg\installed
  - c:\projects\zeloengine\dep

install:
  - cd c:\projects\zeloengine
  - tools\setup\setup_appveyor.bat

before_build:
  - cd c:\projects\zeloengine
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_15" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_15" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd.bat" -arch=x64 -host_arch=x64
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_14" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_14" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\vcvarsx86_amd64.bat"
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MINGW_W64_5_3" set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MINGW_W64_6_3" set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MINGW_W64_6_3" set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MINGW_W64_7_2" set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
  - echo.%cmake_args%
  - cmake %cmake_args% -S . -B ./build -G Ninja

build_script:
  - cd build
  - cmake --build .
