shallow_clone: false

environment:
  matrix:
  - COMPILER: MSVC_16
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#  - COMPILER: MSVC_16
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build:
  verbosity: detailed
  parallel: true

install:
  - Tools\Setup\setup.bat

before_build:
  - cmd: cd C:\projects\zeloengine
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64
#  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x64 -host_arch=x64

#######################################################################################
# we can use Ninja for all configurations
#######################################################################################
build_script:
  - Tools\Build\build_vs2019.bat
