environment:
  matrix:
  - COMPILER: MSVC_16
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build:
  verbosity: detailed
  parallel: true

cache:
  - c:\projects\zeloengine\dep\src\vcpkg\installed\

install:
  - cd c:\projects\zeloengine
  - cd tools\setup\
  - setup.bat

before_build:
  - cd c:\projects\zeloengine
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_16" call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64

build_script:
  - echo "hello"
#  - mkdir build_vs2019
#  - cd build_vs2019
#  - cmake -DCMAKE_GENERATOR_PLATFORM=win32 -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G  "Visual Studio 16" ..
#  - cmake --build . --config debug -j 18
