image:
  - Visual Studio 2019

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    # Win32/x86/Debug
    - platform: Win32
      configuration: Debug
      cmake_args: -DCMAKE_SYSTEM_VERSION="10.0.18362.0"
      platform_name: Windows
      COMPILER: MSVC_16
      ARCHITECTURE: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# clone directory
clone_folder: c:\projects\zeloengine

cache:
  - c:\tools\vcpkg\installed
  - c:\projects\zeloengine\dep

install:
  - cd c:\projects\zeloengine
  - tools\setup\setup_appveyor.bat

before_build:
  - cd c:\projects\zeloengine
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64
  - echo.%cmake_args%
  - cmake %cmake_args% -S . -B ./build -G Ninja

build_script:
  - cd build
  - cmake --build .
